name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-26
    timeout-minutes: 15
    steps:
      - name: Select appropriate Xcode version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1.7.0
        with:
          xcode-version: latest-stable
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: SPM tests
        run: swift build

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ["swift:6.2", "swift:6.3"]

    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        run: |
          swift build